// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Intelektika_projektasML.Model
{
    public class ModelInput
    {
        [ColumnName("Review"), LoadColumn(0)]
        public string Review { get; set; }


        [ColumnName("Class"), LoadColumn(1)]
        public string Class { get; set; }


    }
}
